name: Test case 1—10 Numbers
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Run Test Case 1
      run: |
        python find_lowest_number.py test_data/test1_input.txt output1.txt
        diff output1.txt test_data/test1_expected.txt
