name: Test Case 2 - 1 Number
on: [push]
jobs:
  test_one:
    name: Output Number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run python script
      run: |
        python find_lowest_number.py test_data/test2_input.txt output2.txt
        diff output2.txt test_data/test2_expected.txt
